### ISSUE TITLE
Meta Info Layer

### ISSUE THREAD

**Issue by BigKahuna7385** [lkno0705/ISSTracker#171]
- [ ] inegrate second map layer were only meta infos are displayed

- [ ] establish design for new layer

- [ ] change side bar to new function set
