### ISSUE TITLE
Meta info on meta layer

### ISSUE THREAD

**Issue by BigKahuna7385** [lkno0705/ISSTracker#172]
- [ ] launch info

- [ ] budget info

- [ ] astronaut info

- [ ] facilities on earth

- [ ] missions on ISS

- [ ] can be expanded on
